Petunjuk Penggunaan
-------------------

This part of the documentation, which is mostly prose, begins with some
background information about Baka, then focuses on step-by-step
instructions for web development with Baka.

.. toctree::
   :maxdepth: 2

   foreword
   advanced_foreword
   installation
   quickstart


Referensi API
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Catatan Tambahan
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   changelog
   license
   contributing