.. _petunjuk_penggunaan:

Petunjuk Penggunaan
-------------------

Document bagian ini yang penting dari semua bagian untuk memulai,
usahakan mengikuti langkah-langkah satu per satu instruksi dari development web dengan Baka framework.

.. toctree::
   :maxdepth: 2

   foreword
   advanced_foreword
   installation
   quickstart


.. _referensi_api:

Referensi API
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api


.. _catatan_tambahan:

Catatan Tambahan
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   changelog
   license
   contributing